name: Run tests

on: push

# Stop any in-progress workflows if a newer job for that one starts
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Cache pip dependencies
      - run: pip install -r requirements.txt
      - run: pip install pyinstaller

      - name: Run Unit tests
        run: python -m unittest discover -s src
